# Pandas Operations

**There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category.**


---

In [5]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4,5,6,7,8,9,10],
                   'col2':[444,555,666,444,666,333,222,111,222,777],
                   'col3':['India','USA','UK','NZ','Austrlia','Argentina','Rassia','Brazil','France','Belgium' ]})

In [6]:
df

col1  col2       col3
0     1   444      India
1     2   555        USA
2     3   666         UK
3     4   444         NZ
4     5   666   Austrlia
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil
8     9   222     France
9    10   777    Belgium

In [7]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [8]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [9]:
df.head () # first 5 rows (default value is 5)

col1  col2      col3
0     1   444     India
1     2   555       USA
2     3   666        UK
3     4   444        NZ
4     5   666  Austrlia

In [10]:
df.head(3) # Show only first 3 rows

col1  col2   col3
0     1   444  India
1     2   555    USA
2     3   666     UK

In [11]:
df.head(-1) # Show all rows, exclusding last 1 row   # interview question

col1  col2       col3
0     1   444      India
1     2   555        USA
2     3   666         UK
3     4   444         NZ
4     5   666   Austrlia
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil
8     9   222     France

In [12]:
df.head(-10)    # Show all rows, exclusding last 10 rows 


Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [13]:
df.head(-2) # Show all rows, exclusding last 2 rows 

col1  col2       col3
0     1   444      India
1     2   555        USA
2     3   666         UK
3     4   444         NZ
4     5   666   Austrlia
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil

In [14]:
df.head(-100)  # As we have got only 10 rows, excludgin last 100 rows, will nothing to display

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [15]:
df.head(-5)  # # Show all rows, exclusding last 5 rows  which is equiavalent to df.ehad() - display firt 5 rows

col1  col2      col3
0     1   444     India
1     2   555       USA
2     3   666        UK
3     4   444        NZ
4     5   666  Austrlia

In [16]:
df.head(0)

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [17]:
df.tail()  # display last 5 rows

col1  col2       col3
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil
8     9   222     France
9    10   777    Belgium

In [18]:
df.tail(3)  # display last 3 rows

col1  col2     col3
7     8   111   Brazil
8     9   222   France
9    10   777  Belgium

In [19]:
df.tail(-1)   # Diaply all rows excluding first row

col1  col2       col3
1     2   555        USA
2     3   666         UK
3     4   444         NZ
4     5   666   Austrlia
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil
8     9   222     France
9    10   777    Belgium

In [20]:
df.tail(-2)   # Diaply all rows excluding 2 rows

col1  col2       col3
2     3   666         UK
3     4   444         NZ
4     5   666   Austrlia
5     6   333  Argentina
6     7   222     Rassia
7     8   111     Brazil
8     9   222     France
9    10   777    Belgium

In [21]:
len(df.tail(-2))

8

In [22]:
df.tail(-10)   # Diaply all rows excluding 10 rows

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [23]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [24]:
df.index 

RangeIndex(start=0, stop=10, step=1)

In [25]:
# Add one column containing all Nans, one more column containing all zeros, one more column having non zero values and Nans amd few Zero
# Add one string column as well
import numpy as np
df['col3'] = [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
df['col4'] = [0,0,0,0,0,0,0,0,0,0]
df['col5'] = [0,0,np.nan,0,0,np.nan,0,100,0,220]
df['col6'] = ['India','USA','UK','France','Germany','Japan','Raussia','Belgium','Peru','Brazil']
df['col7'] = [0,0,np.nan,0,0,np.nan,0,0,0,0]


In [26]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7'], dtype='object')

In [27]:
df

col1  col2  col3  col4   col5     col6  col7
0     1   444   NaN     0    0.0    India   0.0
1     2   555   NaN     0    0.0      USA   0.0
2     3   666   NaN     0    NaN       UK   NaN
3     4   444   NaN     0    0.0   France   0.0
4     5   666   NaN     0    0.0  Germany   0.0
5     6   333   NaN     0    NaN    Japan   NaN
6     7   222   NaN     0    0.0  Raussia   0.0
7     8   111   NaN     0  100.0  Belgium   0.0
8     9   222   NaN     0    0.0     Peru   0.0
9    10   777   NaN     0  220.0   Brazil   0.0

In [30]:
df.describe()    # shows statistic only for numeric columns and not string column
# count: Does not consider nan for counting rows, see col3 all nans so count is zero, see column col5 having 2 nans so did not consider and has count 8
# mean : all nans will not be considered so (100+220)/8, zero value row will be considered in count so denbominator is 8
# std  : sqrt( ((sum(x-mean) ** 2)/n) ) for a ll x data points
# min  : Minimum value from data frame
# Max  : Maximum value from data frame
# 25%  : First Q1 quartile (after sroting the elements/values of a dataset/dataframe)
# 75%  : Third Q3 quartile (after sroting the elements/values of a dataset/dataframe)

col1    col2  col3  col4        col5  col7
count  10.00000   10.00   0.0  10.0    8.000000   8.0
mean    5.50000  444.00   NaN   0.0   40.000000   0.0
std     3.02765  222.00   NaN   0.0   80.711125   0.0
min     1.00000  111.00   NaN   0.0    0.000000   0.0
25%     3.25000  249.75   NaN   0.0    0.000000   0.0
50%     5.50000  444.00   NaN   0.0    0.000000   0.0
75%     7.75000  638.25   NaN   0.0   25.000000   0.0
max    10.00000  777.00   NaN   0.0  220.000000   0.0

In [31]:
df.describe(include='all')

col1    col2  col3  col4        col5    col6  col7
count   10.00000   10.00   0.0  10.0    8.000000      10   8.0
unique       NaN     NaN   NaN   NaN         NaN      10   NaN
top          NaN     NaN   NaN   NaN         NaN  Brazil   NaN
freq         NaN     NaN   NaN   NaN         NaN       1   NaN
mean     5.50000  444.00   NaN   0.0   40.000000     NaN   0.0
std      3.02765  222.00   NaN   0.0   80.711125     NaN   0.0
min      1.00000  111.00   NaN   0.0    0.000000     NaN   0.0
25%      3.25000  249.75   NaN   0.0    0.000000     NaN   0.0
50%      5.50000  444.00   NaN   0.0    0.000000     NaN   0.0
75%      7.75000  638.25   NaN   0.0   25.000000     NaN   0.0
max     10.00000  777.00   NaN   0.0  220.000000     NaN   0.0

In [32]:
df.std()

col1      3.027650
col2    222.000000
col3           NaN
col4      0.000000
col5     80.711125
col7      0.000000
dtype: float64

In [33]:
df.min()

col1          1
col2        111
col3       None
col4          0
col5          0
col6    Belgium
col7          0
dtype: object

In [34]:
df.max()

col1      10
col2     777
col3    None
col4       0
col5     220
col6     USA
col7       0
dtype: object

In [23]:
df['col2'].std()   # specific column std deviation

222.0

In [35]:
df.col2.std()

222.0

In [24]:
df['col2'].min() # speecific column min 

111

In [25]:
df['col2'].max() 

777

In [26]:
df['col2'].median()       # 50% quartile

444.0

In [31]:
df['col2'].quantile(0.25)    # 25% First Quantile

249.75

In [32]:
df['col2'].quantile(0.5)    # 50% Second Quantile

444.0

In [33]:
df['col2'].quantile(0.75)    # 75% Third Quantile

638.25

In [34]:
df['col2'].quantile(1)    # 100% Fourth Quantile

777.0

In [36]:
df.describe().transpose()   # show aggregate statistics in transpose format

count   mean         std    min     25%    50%     75%    max
col1   10.0    5.5    3.027650    1.0    3.25    5.5    7.75   10.0
col2   10.0  444.0  222.000000  111.0  249.75  444.0  638.25  777.0
col3    0.0    NaN         NaN    NaN     NaN    NaN     NaN    NaN
col4   10.0    0.0    0.000000    0.0    0.00    0.0    0.00    0.0
col5    8.0   40.0   80.711125    0.0    0.00    0.0   25.00  220.0
col7    8.0    0.0    0.000000    0.0    0.00    0.0    0.00    0.0

In [37]:
# Find out unique values from a column of a data frame

df['col2'].unique()        # values 444, 666, 222 are duplicated

array([444, 555, 666, 333, 222, 111, 777], dtype=int64)

In [38]:
a = df['col2'].unique()

In [39]:
type(a)

numpy.ndarray

In [40]:
a

array([444, 555, 666, 333, 222, 111, 777], dtype=int64)

In [41]:
a[0]

444

In [42]:
len(a)

7

In [43]:
df['col3'].unique()     # All Nan values are present

array([nan])

In [54]:
df['col4'].unique()  # All 0 values are present

array([0], dtype=int64)

In [55]:
df['col5'].unique()  # column contains non zero value, nan, 0 

array([  0.,  nan, 100., 220.])

In [56]:
df['col7'].unique() # Contains only 0 and Nans 

array([ 0., nan])

In [57]:
df['col6'].unique() 

array(['India', 'USA', 'UK', 'France', 'Germany', 'Japan', 'Raussia',
       'Belgium', 'Peru', 'Brazil'], dtype=object)

In [44]:
# Find only number of unique values present in the columns
df['col2'].nunique()

7

In [46]:
df

col1  col2  col3  col4   col5     col6  col7
0     1   444   NaN     0    0.0    India   0.0
1     2   555   NaN     0    0.0      USA   0.0
2     3   666   NaN     0    NaN       UK   NaN
3     4   444   NaN     0    0.0   France   0.0
4     5   666   NaN     0    0.0  Germany   0.0
5     6   333   NaN     0    NaN    Japan   NaN
6     7   222   NaN     0    0.0  Raussia   0.0
7     8   111   NaN     0  100.0  Belgium   0.0
8     9   222   NaN     0    0.0     Peru   0.0
9    10   777   NaN     0  220.0   Brazil   0.0

In [45]:
df['col7'].nunique()  # Nan value is not considered

1

In [47]:
df.col3.nunique()             # interview question

0

In [64]:
df['col5'].nunique()    # Nan value is not considered

3

In [65]:
df['col4'].nunique() # All 0 values are present

1

In [68]:
df['col3'].nunique()         # Since all 0 values are present, it would not be considered so output would show as 0 unique values present

0

In [48]:
# Find out unique value and its total frequency (how many times it has occurred)
df['col1'].value_counts()

10    1
9     1
8     1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: col1, dtype: int64

In [49]:
# Find out unique value and its total frequency (how many times it has occurred)
df['col2'].value_counts()


222    2
444    2
666    2
111    1
333    1
555    1
777    1
Name: col2, dtype: int64

In [50]:
# Find out unique value and its total frequency (how many times it has occurred)
print(df['col3'].value_counts())
print('----')
print(df['col4'].value_counts())
print('----')
print(df['col5'].value_counts())
print('----')
print(df['col6'].value_counts())
print('----')
print(df['col7'].value_counts())

Series([], Name: col3, dtype: int64)
----
0    10
Name: col4, dtype: int64
----
0.0      6
220.0    1
100.0    1
Name: col5, dtype: int64
----
Brazil     1
Germany    1
Belgium    1
Japan      1
India      1
UK         1
Raussia    1
USA        1
Peru       1
France     1
Name: col6, dtype: int64
----
0.0    8
Name: col7, dtype: int64


In [51]:
df

col1  col2  col3  col4   col5     col6  col7
0     1   444   NaN     0    0.0    India   0.0
1     2   555   NaN     0    0.0      USA   0.0
2     3   666   NaN     0    NaN       UK   NaN
3     4   444   NaN     0    0.0   France   0.0
4     5   666   NaN     0    0.0  Germany   0.0
5     6   333   NaN     0    NaN    Japan   NaN
6     7   222   NaN     0    0.0  Raussia   0.0
7     8   111   NaN     0  100.0  Belgium   0.0
8     9   222   NaN     0    0.0     Peru   0.0
9    10   777   NaN     0  220.0   Brazil   0.0