In [1]:
import numpy as np

In [2]:
weights = [60,65,70,75]    # in Kgs
heights = [1.60, 1.65, 1.70,1.75]  # in meters

In [3]:
weights

[60, 65, 70, 75]

In [4]:
type(weights)

list

In [5]:
heights

[1.6, 1.65, 1.7, 1.75]

In [7]:
type(heights)

list

In [8]:
id(weights)

1446230685832

In [9]:
id(heights)

1446230686088

In [10]:
bmi = weights/heights ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [11]:
# ND array

npweights = np.array(weights)     # in Kgs


In [12]:
npweights

array([60, 65, 70, 75])

In [13]:
type(npweights)

numpy.ndarray

In [29]:
npweights.shape

(4,)

In [30]:
npweights.ndim

1

In [14]:
npheights = np.array(heights)  # in meters


In [15]:
npheights

array([1.6 , 1.65, 1.7 , 1.75])

In [16]:
type(npheights)

numpy.ndarray

In [17]:
bmi = npweights/npheights ** 2
print(bmi)

[23.4375     23.87511478 24.22145329 24.48979592]


In [18]:
l = [1,2,3]


In [19]:
type(l)

list

In [20]:
l * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [21]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [22]:
alist = [  [11,22], [33,44], [55,66], [77,88], [99,11]   ]

In [23]:
type(alist)

list

In [24]:
alist

[[11, 22], [33, 44], [55, 66], [77, 88], [99, 11]]

In [25]:
arr = np.array(alist)

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88],
       [99, 11]])

In [28]:
arr.shape

(5, 2)

In [31]:
arr.ndim

2

In [32]:
t = 1,

In [33]:
type(t) 

tuple

In [34]:
arr.shape[0]

5

In [35]:
arr.shape[1]

2

In [36]:
arr.shape[-1]

2

In [37]:
npweights

array([60, 65, 70, 75])

In [38]:
npweights[0]

60

In [39]:
npweights[3]

75

In [40]:
npweights[6]

IndexError: index 6 is out of bounds for axis 0 with size 4

In [41]:
arr

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88],
       [99, 11]])

In [42]:
arr[0]

array([11, 22])

In [43]:
arr[1]

array([33, 44])

In [44]:
arr[1][0]

33

In [46]:
arr[4][1]

11

In [47]:
arr[-1]

array([99, 11])

In [49]:
arr[-1][-1]

11

In [50]:
len(arr)

5

In [51]:
arr

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88],
       [99, 11]])

In [53]:
py_list = list(range(200))

In [54]:
py_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [57]:
print(py_list, end=':')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]:

In [58]:
min(py_list)

0

In [59]:
max(py_list)

199

In [60]:
len(py_list)

200

In [61]:
import sys

In [62]:
print(sys.getsizeof(py_list))

1912


In [63]:
al = np.array(py_list)

In [64]:
type(al)

numpy.ndarray

In [65]:
len(al)

200

In [66]:
print(sys.getsizeof(al))

896


In [67]:
lsarr = np.linspace(0,5,10)

In [68]:
lsarr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [78]:
lsa = np.linspace(0,10,10)

In [79]:
lsa

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [76]:
type(lsa)

numpy.ndarray

In [77]:
type(lsa[0])

numpy.float64

In [81]:
print(np.round(lsa))
print(np.round(lsa,1))
print(np.round(lsa,2))
print(np.round(lsa,3))
print(lsa)

[ 0.  1.  2.  3.  4.  6.  7.  8.  9. 10.]
[ 0.   1.1  2.2  3.3  4.4  5.6  6.7  7.8  8.9 10. ]
[ 0.    1.11  2.22  3.33  4.44  5.56  6.67  7.78  8.89 10.  ]
[ 0.     1.111  2.222  3.333  4.444  5.556  6.667  7.778  8.889 10.   ]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [82]:
type(lsa)

numpy.ndarray

In [83]:
lsa

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [84]:
print(lsa)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [85]:
eyearr1 = np.eye(4)    # Indetity matrix has all 1s at digonal , Here no of rows = no of columns
print(eyearr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [86]:
type(eyearr1)

numpy.ndarray

In [87]:
eyearr1.ndim

2

In [88]:
eyearr1.shape

(4, 4)

In [89]:
eyea = np.eye(3)    # Indetity matrix has all 1s at digonal , Here no of rows = no of columns

print(eyea)
print(eyea.shape)
print(eyea.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
2


In [95]:
aa = np.array([ [ [1,2], [3,4]], [[5,6],[7,8]], [[9,10],[11,12]] ])

In [96]:
print(aa)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [97]:
aa.ndim

3

In [98]:
aa.shape

(3, 2, 2)

In [103]:
a = np.array([ [ [1,2], [3,4], [11,22] ], [[5,6],[7,8],[33,44]], [[9,10],[11,12],[55,66]], [[99,100],[110,120],[550,660]]  ])

In [104]:
a

array([[[  1,   2],
        [  3,   4],
        [ 11,  22]],

       [[  5,   6],
        [  7,   8],
        [ 33,  44]],

       [[  9,  10],
        [ 11,  12],
        [ 55,  66]],

       [[ 99, 100],
        [110, 120],
        [550, 660]]])

In [105]:
a.shape

(4, 3, 2)

In [106]:
a.ndim

3

In [107]:
len(a)

4

In [108]:
a

array([[[  1,   2],
        [  3,   4],
        [ 11,  22]],

       [[  5,   6],
        [  7,   8],
        [ 33,  44]],

       [[  9,  10],
        [ 11,  12],
        [ 55,  66]],

       [[ 99, 100],
        [110, 120],
        [550, 660]]])

In [109]:
a[0]

array([[ 1,  2],
       [ 3,  4],
       [11, 22]])

In [110]:
a[0][1]

array([3, 4])

In [111]:
a[0][1][1]

4

In [113]:
a[0][-1][-1]

22

In [114]:
np.random.rand(3,4)

array([[0.13865197, 0.5099738 , 0.77854396, 0.43187031],
       [0.20127809, 0.52819423, 0.28094563, 0.90088085],
       [0.44572207, 0.07950555, 0.79864046, 0.24486413]])

In [115]:
np.random.rand(3,4)

array([[0.15530119, 0.17089826, 0.96312654, 0.70433718],
       [0.1847204 , 0.1974003 , 0.51504862, 0.95102727],
       [0.96053103, 0.0842731 , 0.02241875, 0.14071452]])

In [116]:
randomarray = np.random.randint(1,100,10)
randomarray

array([95, 31, 17, 64,  5, 69, 29, 56, 82,  6])

In [125]:
randomarray = np.random.randint(1,100,10)
randomarray

array([ 6, 98, 43, 14, 45, 81, 58, 30, 80, 52])

In [128]:
# Functions on np array
print(randomarray.min())   
print(randomarray.max())
print(randomarray.argmax())
print(randomarray.argmin())

6
98
1
0


Accessing array elements

In [135]:
arr=np.array(10,20,30,40,50,60,70,80,90,100)

ValueError: only 2 non-keyword arguments accepted

In [131]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])

In [132]:
type(arr)

numpy.ndarray

In [133]:
arr.ndim

1

In [134]:
arr.shape

(10,)

In [136]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [137]:
len(arr)

10

In [138]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [139]:
arr[-1]

100

In [140]:
arr[0]

10

In [143]:
arr[3,1,9]

IndexError: too many indices for array

In [142]:
arr[[3,1,9]]

array([ 40,  20, 100])

In [144]:
arr[0:3]

array([10, 20, 30])

In [145]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [146]:
arr[4:5]

array([50])

In [147]:
arr[:4]

array([10, 20, 30, 40])

In [148]:
arr[7:]

array([ 80,  90, 100])

In [151]:
arr[0:9:2]

array([10, 30, 50, 70, 90])

In [152]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [153]:
arr[0:9:3]

array([10, 40, 70])

In [157]:
arr[-1::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [161]:
arr[-1:-11:-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [162]:
# Lets define new array 
arr = np.arange(10)

In [163]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
arr[0:5] = 100 

In [165]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [166]:
arr[:] = 1000

In [167]:
arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [168]:
arr = 2000

In [169]:
arr

2000

In [170]:
type(arr)

int

In [171]:
mainarr = np.arange(1,11)
mainarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
mainarrslice = mainarr[1:5]
mainarrslice

array([2, 3, 4, 5])

In [173]:
mainarrslice[:] = 100
mainarrslice

array([100, 100, 100, 100])

In [174]:
mainarr

array([  1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [175]:
id(mainarr)

1446276243248

In [176]:
id(mainarrslice)

1446276240128

In [181]:
id(mainarr[0])

1446279227600

In [179]:
id(mainarrslice[0])

1446279227600

In [182]:
len(mainarrslice)

4

In [183]:
arrcopy = mainarr.copy()

In [184]:
arrcopy

array([  1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [185]:
mainarr

array([  1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [186]:
id(mainarr), id(arrcopy)

(1446276243248, 1446271071296)

In [187]:
a = np.arange(1,11)

In [188]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [189]:
a[-1::-1] 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [190]:
a[::-1] 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [191]:
a[-1:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [192]:
a[-1:-11:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [193]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [195]:
arr[arr>5]

array([6, 7, 8, 9])

In [196]:
arr[ np.logical_and(arr>0, arr<6) ] 

array([1, 2, 3, 4, 5])

In [ ]:
arr[ np.logical_or(arr>0, arr<6) ] 

In [197]:
mat = np.arange(1,26)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [198]:
mat.ndim

1

In [199]:
mat.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [200]:
mat.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [203]:
mat = np.arange(1,17)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [208]:
b = mat.reshape(4,4)

In [206]:
a = mat.reshape(2,4,2)

In [207]:
a.shape

(2, 4, 2)

In [209]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [211]:
np.sum(b,axis=1)       # rowwise addition

array([10, 26, 42, 58])

In [212]:
np.sum(b,axis=0) 

array([28, 32, 36, 40])

In [214]:
np.sum(b)

136

In [215]:
b.sum()

136

In [216]:
np_list = np.array(range(2,21,2))

In [217]:
np_list.mean()

11.0

In [218]:
np_list

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [219]:
np_list.sum()

110

In [221]:
len(np_list)

10

In [222]:
np_list.sum()/len(np_list)

11.0

In [223]:
np.median(np_list)

11.0

In [226]:
l = np.array([1,2,3,4,5,np.nan])

In [227]:
l

array([ 1.,  2.,  3.,  4.,  5., nan])

In [228]:
l.mean()

nan

In [231]:
np.median(l)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)


nan

In [232]:
np.mode(l)

AttributeError: module 'numpy' has no attribute 'mode'

In [243]:
a_np_array= np.array([6, 3, 9, 6,-3,-3, 6,0,0,0,0, 3,3,5, 9, -2,-3,-2,-2,-2, 3,6,1,1,1,1])

In [244]:
from scipy import stats

In [248]:
a=stats.mode(a_np_array)

In [249]:
a

ModeResult(mode=array([-2]), count=array([4]))

In [250]:
type(a)

scipy.stats.stats.ModeResult

In [251]:
a[0]

array([-2])

In [252]:
a[1]

array([4])

In [253]:
np.random.seed(1)
x = np.random.randn(10)

In [254]:
x

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [259]:
np.random.seed(10)
x = np.random.randn(10)

In [260]:
x

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [262]:
a = np.array([2,8,4,6,1,7])

In [263]:
a

array([2, 8, 4, 6, 1, 7])

In [264]:
a.sort()

In [265]:
a

array([1, 2, 4, 6, 7, 8])

In [266]:
-np.sort(-a)

array([8, 7, 6, 4, 2, 1])

In [267]:
np.sort?

In [268]:
np.sort(-a)

array([-8, -7, -6, -4, -2, -1])

In [269]:
-np.sort(a)

array([-1, -2, -4, -6, -7, -8])

In [2]:
import numpy as np

In [13]:
aa = np.array([[1,4],[6,5]])

In [14]:
aa

array([[1, 4],
       [6, 5]])

In [10]:
np.sort(aa, axis=None) 

array([1, 4, 5, 6])

In [15]:
np.sort(aa, axis=0)

array([[1, 4],
       [6, 5]])

In [16]:
np.sort(aa, axis=1)

array([[1, 4],
       [5, 6]])

In [17]:
# Unique
array = np.array([10,20,10,40,20,10,20,40,20])
u = np.unique(array,return_counts=False) 

In [18]:
u

array([10, 20, 40])

In [19]:
u1 = np.unique(array,return_counts=True) 

In [20]:
u1

(array([10, 20, 40]), array([3, 4, 2], dtype=int64))